/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as CompleteBookIdRouteImport } from './routes/complete.$bookId'
import { Route as ScanBookIdRouteImport } from './routes/scan.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteBookIdRoute = CompleteBookIdRouteImport.update({
  id: '/complete/$bookId',
  path: '/complete/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanBookIdRoute = ScanBookIdRouteImport.update({
  id: '/scan/$bookId',
  path: '/scan/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/complete/$bookId': typeof CompleteBookIdRoute
  '/scan/$bookId': typeof ScanBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/complete/$bookId': typeof CompleteBookIdRoute
  '/scan/$bookId': typeof ScanBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/complete/$bookId': typeof CompleteBookIdRoute
  '/scan/$bookId': typeof ScanBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/registry' | '/complete/$bookId' | '/scan/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/registry' | '/complete/$bookId' | '/scan/$bookId'
  id: '__root__' | '/' | '/registry' | '/complete/$bookId' | '/scan/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistryRoute: typeof RegistryRoute
  CompleteBookIdRoute: typeof CompleteBookIdRoute
  ScanBookIdRoute: typeof ScanBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete/$bookId': {
      id: '/complete/$bookId'
      path: '/complete/$bookId'
      fullPath: '/complete/$bookId'
      preLoaderRoute: typeof CompleteBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$bookId': {
      id: '/scan/$bookId'
      path: '/scan/$bookId'
      fullPath: '/scan/$bookId'
      preLoaderRoute: typeof ScanBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistryRoute: RegistryRoute,
  CompleteBookIdRoute: CompleteBookIdRoute,
  ScanBookIdRoute: ScanBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
